services:

  postgres:
    image: postgres:16
    container_name: payment-postgres
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_pass
    ports:
      - "5432:5432"
    volumes:
      - payment_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payment_user -d paymentdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: payment-redis
    ports:
      - "6379:6379"
    volumes:
      - payment_redis_data:/data

volumes:
  payment_postgres_data:
  payment_redis_data: