spring.application.name=payment-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/paymentdb
spring.datasource.username=payment_user
spring.datasource.password=payment_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.data.redis.host=localhost
spring.data.redis.port=6379

payment.gateway.mock.fail-attempts=0
payment.retry.max-attempts=3